# Generated by Django 5.1.3 on 2024-12-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='CartItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
