# Generated by Django 5.1.3 on 2024-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_shoppingcart_cartitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
