# Generated by Django 5.1.3 on 2024-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_logged_in'),
  ]
    operations = [
        migrations.AlterField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
