# Generated by Django 5.1.3 on 2025-01-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
