# Generated by Django 5.1.3 on 2025-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
