"""
Django settings for ecommerce_backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

KLUSTER_API_KEY = config("KLUSTER_API_KEY")

SECRET_KEY = 'django-insecure-7!90f&(_e4=8hkd&8)&3pc!l_mmxl7$8mbvejy$m&d^())#4wj'

DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Adjust for your frontend's URL
    "https://hamza-masoud.github.io",
]



INSTALLED_APPS = [
    'admin_tools_stats',
    'django_nvd3',
    'django_light',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'accounts',
    'chartapp.apps.ChartappConfig',
    'chatbot',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ecommerce_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'ecommerce_backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',      
        'NAME': 'neondb',                                                         # Replace with your database name
        'USER': 'neondb_owner',                                                        # Replace with your PostgreSQL username
        'PASSWORD': 'npg_YtVWT2RCAxE8',                                                 # Replace with your PostgreSQL password
        'HOST': 'ep-delicate-tooth-a2ldr12j.eu-central-1.aws.neon.tech',               # Use 'localhost' for local PostgreSQL server
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
            'options': '-c search_path=public'
            },
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':
        ['rest_framework.authentication.TokenAuthentication'],
     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',    
    

}
SPECTACULAR_SETTINGS = {
    'TITLE': 'Your API Docs',
    'DESCRIPTION': 'Automated Swagger docs for Django REST Framework',
    'VERSION': '1.0.0',
}

STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'in-v3.mailjet.com'  
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '6452297de9d3ab192c4b8d643487412a'  
EMAIL_HOST_PASSWORD = '9c18073363ee23891343ad327e141fa8'
DEFAULT_FROM_EMAIL = 'abomoh975@gmail.com'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
STRIPE_PUBLIC_KEY ='pk_test_51QcpDF2Nr0G4DsWGvWHQdeFHYDjIRqDMkeuJMxqsbEWJmvyZs99h9aPSwePszOlymsise2QSBdxYI0z6VCIvE5tj00csMzJHk7'
STRIPE_SECRET_KEY ='sk_test_51QcpDF2Nr0G4DsWGo2PDTID9jANstyjgTuX7PlkDaZovPxWrk7Fa1qzZkeILYEwpjD17whsvEdAntXgQpsSoWMZM001abR6CnS'
STRIPE_WEBHOOK_KEY ='whsec_0T7QKB7QnzTZiquzK4SIYqEvm9y7gaVp'
